export const headLeedurs = [
  {
    group: 'Alpha',
    letter: 'Αα',
    leedur1: 'Jasmine Wu',
    leedur2: 'Justin Wang',
    ig: 'https://www.instagram.com/alpha_frosh_2t2/',
    email: 'alpha@orientation.skule.ca',
  },
  {
    group: 'Beta',
    letter: 'Ββ',
    leedur1: 'Nicola Lawford',
    leedur2: 'Ernie Huergo',
    ig: 'https://www.instagram.com/beta_frosh_2t2/',
    email: 'beta@orientation.skule.ca',
  },
  {
    group: 'Gamma',
    letter: 'Γγ',
    leedur1: 'Julia Wagner',
    leedur2: 'Chase McDougall',
    ig: 'https://www.instagram.com/gamma_frosh_2t2/',
    email: 'gamma@orientation.skule.ca',
  },
  {
    group: 'Delta',
    letter: 'Δδ',
    leedur1: 'Stephanie Perri',
    leedur2: 'Terry Luan',
    ig: 'https://www.instagram.com/delta_frosh_2t2/',
    email: 'delta@orientation.skule.ca',
  },
  {
    group: 'Zeta',
    letter: 'Ζζ',
    leedur1: 'Ammar Vora',
    leedur2: 'Rhythm Loomba',
    ig: 'https://www.instagram.com/zeta_frosh_2t2/',
    email: 'zeta@orientation.skule.ca',
  },
  {
    group: 'Theta',
    letter: 'Θθ',
    leedur1: 'Geoffrey Jiang',
    leedur2: 'Renee Slen',
    ig: 'https://www.instagram.com/theta_frosh_2t2/',
    email: 'theta@orientation.skule.ca',
  },
  {
    group: 'Iota',
    letter: 'Ιι',
    leedur1: 'Cassey Shao',
    leedur2: 'Lincoln Macdonald',
    ig: 'https://www.instagram.com/iota_frosh_2t2/',
    email: 'iota@orientation.skule.ca',
  },
  {
    group: 'Kappa',
    letter: 'Κκ',
    leedur1: 'Gianpaolo Povolo',
    leedur2: 'Annie Pham',
    ig: 'https://www.instagram.com/kappa_frosh_2t2/',
    email: 'kappa@orientation.skule.ca',
  },
  {
    group: 'Lambda',
    letter: 'Λλ',
    leedur1: 'Dina Aynalem',
    leedur2: 'Navin Vanderwert',
    ig: 'https://www.instagram.com/lambda_frosh_2t2/',
    email: 'lambda@orientation.skule.ca,',
  },
  {
    group: 'Nu/Ni',
    letter: 'Νν',
    leedur1: 'William Jereza',
    leedur2: 'Olivia Fredrickson',
    ig: 'https://www.instagram.com/nu_frosh_2t2/',
    email: 'ninu@orientation.skule.ca',
  },
  {
    group: 'Omicron',
    letter: 'Οο',
    leedur1: 'Nicole Amenta',
    leedur2: 'Mike Cortese',
    ig: 'https://www.instagram.com/omicron_frosh_2t2/',
    email: 'omicron@orientation.skule.ca',
  },
  {
    group: 'Pi',
    letter: 'Ππ',
    leedur1: 'Darsh Jain',
    leedur2: 'Nikkie Bonon',
    ig: 'https://www.instagram.com/pi_frosh_2t2/',
    email: 'pi@orientation.skule.ca',
  },
  {
    group: 'Rho',
    letter: 'Ρρ',
    leedur1: 'Vuk Kliska',
    leedur2: 'Amanda Plotnik',
    ig: 'https://www.instagram.com/rho_frosh_2t2/',
    email: 'rho@orientation.skule.ca',
  },
  {
    group: 'Sigma',
    letter: 'Σσ',
    leedur1: 'Sunny Park',
    leedur2: 'Soliman Ali',
    ig: 'https://www.instagram.com/sigma_frosh_2t2/',
    email: 'sigma@orientation.skule.ca',
  },
  {
    group: 'Tau',
    letter: 'Ττ',
    leedur1: 'Katie Stephens',
    leedur2: 'Tudor Sigmund',
    ig: 'https://www.instagram.com/tau_frosh_2t2/',
    email: 'tau@orientation.skule.ca',
  },
  {
    group: 'Upsilon',
    letter: 'Υυ',
    leedur1: 'Jake Blimkie',
    leedur2: 'Isabella Petrocelli',
    ig: 'https://www.instagram.com/upsilon_frosh_2t2/',
    email: 'upsilon@orientation.skule.ca',
  },
  {
    group: 'Phi',
    letter: 'Φφ',
    leedur1: 'Annam Shamas',
    leedur2: 'Daniel Tykei',
    ig: 'https://www.instagram.com/phi_frosh_2t2/',
    email: 'phi@orientation.skule.ca',
  },
  {
    group: 'Chi',
    letter: 'Χχ',
    leedur1: 'Hazel Fricska',
    leedur2: 'Purushoth Thavendran',
    ig: 'https://www.instagram.com/chi_frosh_2t2/',
    email: 'chi@orientation.skule.ca',
  },
  {
    group: 'Psi',
    letter: 'Ψψ',
    leedur1: 'Justin Chang',
    leedur2: 'Stephanie Lu',
    ig: 'https://www.instagram.com/psi_frosh_2t2/',
    email: 'psi@orientation.skule.ca',
  },
  {
    group: 'Omega',
    letter: 'Ωω',
    leedur1: 'Joy Lai',
    leedur2: 'Anaqi Afendi',
    ig: 'https://www.instagram.com/omega_frosh_2t2/',
    email: 'omega@orientation.skule.ca',
  },
];
