export const list = [
  {
    number: '1',
    name: 'Jump into ANY body of water',
    category: 'The Classics',
    points: '300',
    isHidden: false,
  },
  {
    number: '2',
    name: '5 condoms you got for free',
    category: 'The Classics',
    points: '75',
    isHidden: false,
  },
  {
    number: '3',
    name: 'A pinata, filled to the brim',
    category: 'The Classics',
    points: '200',
    isHidden: false,
  },
  {
    number: '55',
    name: 'Teach family members/roommates the dance to Give It Up',
    category: 'uNpRecEdeNTed tIMEs',
    points: '100',
    isHidden: false,
  },
  {
    number: '82',
    name: 'Paint a rennaissance style portrait of your pet',
    category: 'Arts and Craps',
    points: '100',
    isHidden: false,
  },
  {
    number: '83',
    name: 'Paint an elegant portrait of your Scunt Subcoms on an deep sea adventure ',
    category: 'Arts and Craps',
    points: '200',
    isHidden: false,
  },
  {
    number: '297',
    name: 'Explain why Myhal and Bahen are so poorly designed',
    category: 'Number 1 in Canada, number 17 in the world',
    points: '300',
    isHidden: false,
  },
  {
    number: '442',
    name: 'A diamond sword on the Skulecraft Server',
    category: 'Faculty of Attempted Socialization and Extroversion',
    points: '80',
    isHidden: false,
  },
  {
    number: '574',
    name: 'Say a limerick on Limerick road',
    category: "It's pronounced *chronnoe*",
    points: '75',
    isHidden: false,
  },
  {
    number: '777',
    name: 'Sit on an egg without breaking it (please clean it up afterwards)',
    category: 'Weird flex but ok',
    points: '100',
    isHidden: false,
  },
  {
    number: '796',
    name: 'Procure or fabricate flower girl attire for the Ultimate F!rosh',
    category: 'The Royal Wedding',
    points: '100',
    isHidden: false,
  },
];
