export const fields = {
  'Step 1': {
    medicalInfo: {
      type: 'text',
      inputType: 'textArea',
      label: 'Allergies and/or medical condistions',
      placeholder: 'Nut allergy',
      hasRestrictedInput: true,
      isRequiredInput: false,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-medicalInfo',
    },
    medication: {
      type: 'text',
      inputType: 'text',
      label: 'Medication (e.g. Epi-Pen, inhaler, ...)',
      placeholder: 'Carries 2 epi-pens',
      hasRestrictedInput: true,
      isRequiredInput: false,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-medication',
    },
    torontoIslandTrip: {
      type: 'radio',
      label:
        'Would you be interested in a trip to Toronto Islands on one of the evenings during F!rosh Week? (At a small additional cost)',
      values: ['Yes', 'No'],
      initialSelectedIndex: 1,
    },
    shirtSize: {
      type: 'dropdown',
      label: 'T-shirt size',
      values: ['S', 'M', 'L', 'XL'],
      initialSelectedIndex: 1,
    },
    scunt: {
      type: 'radio',
      label:
        'Would you like to participate in Havenger Scunt? (It will take place on the evening of Wednesday, September 7th)',
      values: ['Yes', 'No'],
      initialSelectedIndex: 1,
    },
    nightlife: {
      type: 'radio',
      label:
        'Would you be interested in an overnight retreat on September 10th -11th? (at an Additional cost)',
      values: ['Yes', 'No'],
      initialSelectedIndex: -1,
    },
    summerLocation: {
      type: 'text',
      inputType: 'text',
      label: 'Where will you be located for the majority of the summer?',
      placeholder: 'Toronto, Canada',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter your current city and country.',
      localStorageKey: 'registration-medication',
    },
    moveToToronto: {
      type: 'dropdown',
      label:
        'If you are not in the GTA already, approximately when are you planning to move to Toronto?',
      values: [
        'N/A',
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      initialSelectedIndex: 0,
    },
    allergies: {
      type: 'checkbox',
      label: 'Please select the following dietary restrictions or allergies if any.',
      values: [
        'Lactose Intolerance',
        'Gluten Intolerance',
        'Vegetarian',
        'Vegan',
        'Kosher',
        'Dairy-Free',
        'Pork',
        'Nuts',
      ],
    },
    allergiesMore: {
      type: 'text',
      inputType: 'text',
      label:
        'If there are any other restrictions not listed above, please write them in the box below.',
      placeholder:
        'If there are any other restrictions not listed above, please write them in the box below.',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter your current city and country.',
      localStorageKey: 'registration-allergies',
    },
    commuterProgram: {
      type: 'radio',
      label:
        'Will you take part in the Commuter Program (you can still sign up via links on Instagram and Frosh week website)?',
      values: ['Yes', 'No', 'Put me on the waitlist'],
      initialSelectedIndex: 1,
    },
    // enable if selected yes to above...
    areaGTA: {
      type: 'text',
      inputType: 'text',
      label:
        'What area of the GTA do you live in? Please enter your postal code. (This information is used only to pair you with commuters in your area for the purpose of this program)',
      placeholder: 'M5S 3K1',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a valid postal code.',
      localStorageKey: 'registration-areaGTA',
    },
    // enable if selected yes to above...
    chestnutStay: {
      type: 'radio',
      label: 'Would you like to stay up at Chestnut during Frosh week with an additional cost?',
      values: ['Yes', 'No'],
      initialSelectedIndex: -1,
    },
    photograph: {
      type: 'radio',
      label: 'Are you okay with being photographed during Frosh Week?',
      values: ['Yes', 'No'],
      initialSelectedIndex: 1,
    },
    accessibility: {
      type: 'text',
      inputType: 'text',
      label: "Do you have any accessibility requirements you'd like to share with us?",
      placeholder:
        'I would like to be able to access a quiet space to relax when the activities get overwhelming',
      hasRestrictedInput: true,
      isRequiredInput: false,
      errorMessage: 'Please enter a valid postal code.',
      localStorageKey: 'registration-areaGTA',
    },
    //only show if previous one
    accomadation: {
      type: 'radio',
      label: 'Would you like us to reach out to you about how we can best accomodate you?',
      values: ['Yes', 'No'],
      initialSelectedIndex: -1,
    },

    firstName: {
      type: 'text',
      inputType: 'text',
      label: 'What is your Full Name? (First & Last)',
      placeholder: 'John',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a valid name',
      localStorageKey: 'registration-firstName',
    },
    lastName: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Doe',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a valid name',
      localStorageKey: 'registration-lastName',
    },
    preferredName: {
      type: 'text',
      inputType: 'text',
      label: 'What is your preferred name?',
      placeholder: 'Joey',
      hasRestrictedInput: true,
      isRequiredInput: false,
      errorMessage: '',
      localStorageKey: 'registration-preferredName',
    },
    birthdate: {
      type: 'text',
      inputType: 'date',
      label: 'What is your birthday?',
      placeholder: '1852-12-25',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a valid date',
    },
    pronouns: {
      type: 'text',
      inputType: 'text',
      label: 'What is your pronoun?',
      placeholder: 'He/Him',
      hasRestrictedInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-pronouns',
    },
    shippingLine1: {
      type: 'text',
      inputType: 'text',
      label: 'What is your shipping address? (for frosh kits)',
      placeholder: '123 Park Street',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    shippingLine2: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Unit 123',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    shippingCity: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Toronto',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    shippingProvince: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Ontario',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    shippingPostalCode: {
      type: 'text',
      inputType: 'text',
      placeholder: 'M9R2J0',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    shippingPostalCountry: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Canada',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    discipline: {
      type: 'dropdown',
      label: 'Discipline',
      values: ['idk', 'idk', 'idk', 'idk', 'djwakdwhjadjwahdkjwahdjkwahdadwh'],
      initialSelectedIndex: 1,
    },
    utorid: {
      type: 'text',
      inputType: 'text',
      label: 'UtorID',
      placeholder: 'doejohn2',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a UtorID',
      localStorageKey: 'registration-utorid',
    },
    // "email":{
    //   "type":"text",
    //   "inputType":"text",
    //   "label":"Email",
    //   "placeholder":"Email",
    //   "hasRestrictedInput":true,
    //   "isRequiredInput":true,
    //   "errorMessage":"Missing field",
    //   "localStorageKey":"registration-email"
    // },
    // "password":{
    //   "type":"text",
    //   "inputType":"password",
    //   "label":"Password",
    //   "placeholder":"Password",
    //   "hasRestrictedInput":true,
    //   "isRequiredInput":true,
    //   "errorMessage":"Missing field"
    // },
    //Format the phone number as asked
    phoneNumberAreaCode: {
      type: 'text',
      inputType: 'text',
      label: "What's your phone number?",
      placeholder: '+1',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-phoneNumberAreaCode',
    },
    phoneNumber: {
      type: 'text',
      inputType: 'text',
      placeholder: '416-123-45678',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-phoneNumber',
    },
    instagram: {
      type: 'text',
      inputType: 'text',
      label: "What's your Instagram handle?",
      placeholder: '@bestfrosh',
      hasRestrictedInput: true,
      isRequiredInput: false,
      localStorageKey: 'registration-instagram',
    },
    emergencyContactName: {
      type: 'text',
      inputType: 'text',
      label: 'Emergency contact full name (first & last):',
      placeholder: 'Jane Doe',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Please enter a valid name',
      localStorageKey: 'registration-emergencyContactName',
    },
    emergencyContactRelationship: {
      type: 'text',
      inputType: 'text',
      label: "What is your emergency contact's relationship to you?",
      placeholder: 'Mother',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-emergencyContactRelationship',
    },
    emergencyContactNumberAreaCode: {
      type: 'text',
      inputType: 'text',
      label: "What is your emergency contact's phone number?",
      placeholder: '+1',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-emergencyContactNumberAreaCode',
    },
    emergencyContactNumber: {
      type: 'text',
      inputType: 'text',
      placeholder: '416-123-45678',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
      localStorageKey: 'registration-emergencyContactNumber',
    },
    residencyLine1: {
      type: 'text',
      inputType: 'text',
      label: 'What is your residency address? (one you will live at during frosh)',
      placeholder: '123 Park Street',
      hasRestrictedInput: true,
      isRequiredInput: false,
      errorMessage: 'Missing field',
    },
    residencyLine2: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Unit 123',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    residencyCity: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Toronto',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    residencyProvince: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Ontario',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    residencyPostalCode: {
      type: 'text',
      inputType: 'text',
      placeholder: 'M9R2J0',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
    residencyPostalCountry: {
      type: 'text',
      inputType: 'text',
      placeholder: 'Canada',
      hasRestrictedInput: true,
      isRequiredInput: true,
      errorMessage: 'Missing field',
    },
  },
};
