export const instagramAccounts = {
  Alpha: 'https://www.instagram.com/alpha.frosh.2t5/',
  Beta: 'https://www.instagram.com/beta.frosh.2t5/',
  Iota: 'https://www.instagram.com/iota.frosh.2t5/',
  Phi: 'https://www.instagram.com/phi.frosh.2t5/',
  Psi: 'https://www.instagram.com/psi.frosh.2t5/',
  Rho: 'https://www.instagram.com/rho.frosh.2t5/',
  Zeta: 'https://www.instagram.com/zeta.frosh.2t5/',
  Gamma: 'https://www.instagram.com/gamma.frosh.2t5',
  Omega: 'https://www.instagram.com/omega.frosh.2t5/',
  Chi: 'https://www.instagram.com/chi.frosh.2t5/',
  Upsilon: 'https://www.instagram.com/upsilon.frosh.2t5/',
  Pi: 'https://www.instagram.com/pi.frosh.2t5/',
  Nu: 'https://www.instagram.com/ninu.frosh.2t5/',
  Delta: 'https://www.instagram.com/delta.frosh.2t5/',
  Sigma: 'https://www.instagram.com/sigma.frosh.2t5/',
  Tau: 'https://www.instagram.com/tau.frosh.2t5/',
  Kappa: 'https://www.instagram.com/kappa.frosh.2t5/',
  Theta: 'https://www.instagram.com/theta.frosh.2t5/',
  Lambda: 'https://www.instagram.com/lambda.frosh.2t5/',
  Omicron: 'https://www.instagram.com/omicron.frosh.2t5/',
};
