export const instagramAccounts = {
  Alpha: 'https://www.instagram.com/alpha.frosh.2t6/',
  Beta: 'https://www.instagram.com/beta.frosh.2t6/',
  Gamma: 'https://www.instagram.com/gamma.frosh.2t6/',
  Delta: 'https://www.instagram.com/delta.frosh.2t6/',
  Zeta: 'https://www.instagram.com/zeta.frosh.2t6/',
  Theta: null,
  Iota: 'https://www.instagram.com/iota.frosh.2t6/',
  Kappa: 'https://www.instagram.com/kappa.frosh.2t6/',
  Lambda: 'https://www.instagram.com/lambda.frosh.2t6/',
  Nu: null,
  Omicron: 'https://www.instagram.com/omicron.frosh.2t6/',
  Pi: 'https://www.instagram.com/pi.frosh.2t6/',
  Rho: null,
  Sigma: 'https://www.instagram.com/sigma.frosh.2t6/',
  Tau: 'https://www.instagram.com/tau.frosh.2t6/',
  Upsilon: 'https://www.instagram.com/upsilon.frosh_2t6/',
  Phi: 'https://www.instagram.com/phi.frosh.2t6/',
  Chi: 'https://www.instagram.com/chi.frosh_2t6/',
  Psi: 'https://www.instagram.com/psi.frosh_2t6/',
  Omega: 'https://www.instagram.com/omega.frosh.2t6/',
};
