export const rules = {
  start: [
    {
      title: 'Eligibility',
      sub: 'To compete in the Havenger Scunt, one must be:',
      items: [
        'Human, or near human (Engineering Science students will be accepted).',
        'A F!rosh (2T5!)',
        'Currently enrolled within the Faculty of Applied Science and Engineering at the University of Toronto.',
        'Have officially registered for the event.',
        'Screened and have completed UCheck before arrival if participating in-person.',
      ],
    },
    {
      title: 'Registration',
      sub: 'The following applies for registration:',
      items: [
        'Registration will be done through the same portal as the regular F!rosh Week registration.',
        'It will be a checkbox on that form, and you can register retroactively by editing your responses on that website.',
      ],
    },
    {
      title: 'Teams',
      sub: 'The team structure of Havenger Scunt will be as follows:',
      items: [
        'Contestants will be assigned randomly to 1 of 10 teams to approximate fairness upon registration.',
        'If registered for in-person participation, each contestant will also be assigned to a “meetup group” of 10-15 F!rosh and 1-2 leedurs within those teams, and must stick with that group for the duration of the event for COVID-19 safety reasons. <ol><li>These groups will be roughly assigned based on address so hopefully train rides won’t be lonely.</li><li>Under no circumstances will the contestants intermingle with other groups in person besides distant banter.</li><li>It is permissible to perform items solo, but again don’t rope anyone else in.</li><li>COVID-19 protocols must still be followed within the groups.</li></ol>',
        'If not registered for in-person participation, the contestants will perform and record the items solo.',
      ],
    },
    {
      title: 'Timing',
      sub: 'The timing of Havenger Scunt will be as follows:',
      items: [
        'The event shall begin on Wednesday, September 8th at 5:30pm EST. At this time, the Cannon will fire and scunt.skule.ca will go live with the list, as will all the commands on our Discord server. Oh yeah and the judges will rise from their upper year slumber too.',
        'There will be a livestream that will go live slightly earlier at 5:15pm',
        'The Royal Wedding will occur at approximately 9:30PM',
        'The event will end on Wednesday, September 8th at 11:00pm EST. There will be a 30-minute warning announcement.',
      ],
    },
    {
      title: 'Scoring Eligibility',
      sub: 'To be eligible for points a team must complete an item on the list and:',
      items: [
        'Present sufficient proof of completion of said item to a judge: photo, video, or other documentation submitted via our website or Discord, or perform the item live before the judge.',
        '<strong>***The item must be on the list.***</strong>',
        'Not be violating Federal, Provincial, or Municipal Law, or University Policy. If an item appears illegal or impossible, it is meant to illicit a creative (and legal) solution. <ol><li>This includes trespassing inside university buildings.</li><li>Points WILL be deducted if laws are broken or anything particularly reckless is done!</li></ol>',
        '<strong>***The item must be on the list.***</strong>',
        'Said item must have been completed by (at minimum) one freshman (F!rosh) from said team. Items completed by leaders alone will be ineligible for scoring.',
        '<strong>***The item must be on the list.***</strong>',
        'It is encouraged to let Judges keep physical items brought in person (like a bigass fucking dildo) as part of the Havenger Scunt unless the items have a significant sentimental value.',
        '<strong>***The item must be on the list.***</strong>',
        'If there is any mess created by performing an item in-person, it must be cleaned up or you will not get the points.',
        '<strong>***The item must be on the list.***</strong>',
        'The item should not harm to the performant, including but not limited to: physical harm, illness, inebriety, allergic reactions, vomiting, or anything else that requires the attention of SkuleTM Patrol.',
        '<strong>***The item must be on the list.***</strong>',
        'Read the room. Don’t perform an item that makes anyone in the general public uncomfortable.',
        '<strong>***The item must be on the list.***</strong>',
        'Media consent must be acquired from strangers prior to all videos/photos which involves them. All media including strangers will NOT be shared on social media, and will only be seem on the submission website, and potentially the livestream.',
        '<strong>***Did we mention that the item must be on the fucking list?***</strong>',
        'Alright fine, if you clear it with a particular judge beforehand, you may perform something not on the list to THAT JUDGE IN PARTICULAR as a “Bring a Reward In Beneficial to Expert” (B.R.I.B.E.). But again ONLY if you clear it beforehand, otherwise <strong>***The item must be on the list.***</strong>',
      ],
    },
    {
      title: 'Judging',
      items: [
        'Items can be submitted via the website, Discord, or performed in person to a judge, starting at 5:30 and ending at 11 as with the rest of the event.',
        'There will be 16 total judges for Havenger Scunt.',
        'Judges will come in pairs, and at a given time there will be 3 pairs judging online submissions (in a very secret undisclosed location), and 5 pairs available to be bothered in person.<ol><li>This will be subject to change as the nite goes on.</li></ol>',
        'Those 5 pairs will each be at one of 5 stations around campus (check out our handy map).<ol><li>If one of the stations will be moved to online judging, an announcement will be made.</ol></li>',
        'The pairs of Judges will rotate through each of the 8 total stations.',
        '<strong>***DO NOT and we repeat DO NOT disturb the judges as they are rotating throughout the stations***</strong>',
        '<strong>***And if you attempt to invade our top secret hideout, Emma will personally fuck you up***</strong>',
        'There will be Skule Patrollers, Cannon Guards, and hand sanitizer at each station to promote safety and Covid regulation compliance at each station.<ol><li>The Guards and Patrollers must be obeyed, if they get sad points will be deducted.</li></ol>',
        'There will be a livestream available for all Skuligans, where items which have Media Consent from the submitter may be reacted to and judged live on stream by some judges on the livestream.',
        'The actual number of points awarded per item will be roughly based on how creative/impressive the judge thinks the item is.<ol><li>Items can be resubmitted to potentially obtain more points. The higher of the multiple submissions will be the one counted.</li><li>If you go particularly above and beyond expectations, there is a slim possibility to earn slightly above the maximum number of points for a given item.</li></ol>',
      ],
    },
    {
      title: 'Bribery',
      sub: "The Judges are unwavering in their tremendously unbiased and fair judging practices. That being said, you might want to check out the Judges page on the website…. It is permissible to “Bring a Reward In Beneficial to Expert” (B.R.I.B.E.). No liquid assets or anything else of substantial value should be among your 'Rewards'.",
      items: [],
    },
    {
      title: 'COVID-19 Protocols',
      items: [
        'As stated earlier, in order to participate in-person you must have completed Ucheck and be screened by it prior to arrival.',
        'All campus buildings will be closed during the event, and cannot be accessed by contestants.<ol><li>If you need to pee, the campus has a very nice variety of shrubbery to hide behind.</li></ol>',
        'Follow local safety protocols. If you are being unsafe points will be deducted.',
      ],
    },
    {
      title: 'Guiding Principles',
      sub: 'All bribes must follow the same principles as used when pranking. They are as follows:',
      items: [
        ' Successful school rivalries, competitions, and pranks are built upon mutual respect for people, property and possessions.',
        " A notable prank/kidnapping/mascot theft/ect. is one that leaves the affected group thinking 'Damn, those crafty bastards!'",
      ],
    },
    {
      title: 'The Royal Wedding',
      sub: 'The Royal Wedding is the wedding to bring Godiva’s Crown and Mr. Blue & Gold together eternally. The list items for the Royal Wedding will be accepted by the bride and groom, as well as the SubComm Chairs. The submissions for these items will be opened starting at 8:30pm ish. Each group that wants to claim an item must bring the participating F!rosh and the item to the SubComm Chairs. The wedding will take place at 9:30pm. Only the F!rosh approved beforehand may participate in the wedding. Any F!rosh that interferes during the wedding will be removed from the super secret scene.',
      items: [],
    },
    {
      title: 'Winning',
      sub: 'The group that accumulates the most points, in the absence of any obvious cheating and/or other misconduct, by the end of the night shall be declared the winners.',
      items: [],
    },
    {
      title: 'Prizes',
      sub: "The winners of the Havenger Scunt will receive a super cool first tier prize! The second place team will receive a super cool second tier prize! The third and fourth groups will receive a super cool third tier prize! All of these groups will earn the ability to go to other teams and say 'Neener, neener, etc.', 'HAHAHAHA HAHAHAHA! IN YOUR FACE #%$@*#*$*#!'' or something similar. Essentially bragging rights forever.",
      items: [
        'Prizes will be able for pickup at Engineering Stores later in September, any time this year.',
      ],
    },
    {
      title: 'Havenger Scunt Chairs',
      sub: 'Oh Hey, that’s us!',
      items: [
        'Any and all disputes will be brought before a Head Judge who is infallible - as all decisions are infallible, they are also final.',
        'The Chairs have the reserved right to deduct up to infinity points from any team that leaves a mess in the completion of Scunt Items. Teams should thus clean up their messes to avoid the humiliation and shame that comes with being singled out for leaving a mess.',
        'The Chairs have the reserved right to deduct up to infinity points from any team found to be in violation of Section 15 rules (Kidnapping) as laid out above or for breaking the law. This is only an option for situations that can be resolved to the satisfaction of all parties.',
        'The Chairs have the reserved right to disqualify teams or individuals that are found to be in irreparable breach of these rules. Furthermore, it is a Head Judge’s responsibility to bar judges that have proven to be in breach of their expected conduct.',
        'We may decide to have certain “requests” throughout the nite, do keep in mind that we can give out as many points as we please while the judges have only so many… ;)',
        'Our names are Jerry and Erika. Hi. We think you can find more about us somehow if you try.',
      ],
    },
    {
      title: 'Rules',
      sub: 'These rules are up to the interpretation of the Havenger Scunt Chairs, and may be changed at any time.',
      items: [],
    },
    {
      title: 'kidnapping',
      sub: 'Any kidnapping requested by judges that occurs during the Havenger Scunt must follow this code:',
      items: [
        'In accordance with the second guiding principle the kidnapping should be well planned. Knowing in advance how the kidnapee will respond, or pre-staging the kidnapping is essential for avoiding conflict.',
        'Kidnapping can be done through virtual means and must comply with social distancing and safety guidelines.',
        'Any use of force must desist if the kidnapee is unwilling to participate.',
        'Kidnapees should be fed adequate, if not excessive, amounts of food and beverages.',
        'Conditions for release should be feasible and reasonable. It should also be possible to meet these conditions within a time period of 24 hours.',
        'Consideration emergency release should be given in the case of impeding midterms, exams or other similar situations.',
        'In the case where the guidelines of the “Code” have been respected, both schools should do their best to keep the ensuing discussion/debate between the student societies. If the “Code” was disregarded, however, the victim school has every right to alert the faculty, campus authorities or city police.',
        'Kidnapped individuals can be ransomed to the judges for points over Discord. The amount of points is non-negotiable.',
        'Each kidnapping may only be completed once during the event. So if they tell you that they have already been kidnapped, leave them alone.',
      ],
    },
    {
      title: 'Liability',
      sub: 'The University of Toronto, the Engineering Society, the Orientation Committee, and the Havenger Scunt executive committee will not be held accountable for illegal or unethical actions performed by event participants. The same parties will also not be liable for any injuries sustained through direct or indirect participation in the event.',
      items: [],
    },
  ],
};
